name: python_in_arabic
description: Interactive Python learning app for Arabic users
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_performance: ^0.10.0
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Utilities
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  share_plus: ^10.0.2
  
  # Icons & Animations
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
